---
- name: add user
  hosts: all
  tasks:
  - name: add group
    group:
      name: taro
      gid: 10000
      state: present
  - name: add taro
    user:
      name: taro
      home: /home/taro
      uid: 10000
      shell: /bin/bash
      comment: "Taro Yamada"
      password: $6$OmC3KootOURrqOaP$63rwQ2bSE8op8wXa.ZWzgxm/iGvePTzEL5lOntmkPyYh5Qwh4lWs2DtyoEHcvsbYV5Q6a2ezzrZueb2ydrkhz0
  - name: install package
    yum:
      name: httpd
      state: installed
